local lu = require('luaunit')

require('test/test_array')
require('test/test_degree')
require('test/test_mode')
require('test/test_note')
require('test/test_scale')
require('test/test_chord')
require('test/test_chord_event')
require('test/test_part')
require('test/tracks/test_clip')
require('test/tracks/test_clip_array')
require('test/tracks/test_event')
require('test/tracks/test_event_array')
require('test/test-circleof5ths')

os.exit( lu.LuaUnit.run() )
